### ISSUE TITLE
Externe Links werden im selben Tab geöffnet

### ISSUE THREAD

**Issue by JoKeyser** [HackyHour/Giessen#3]
Ich weiß, es ist nicht dringend, aber jedesmal fällt mir auf dass externe Links auf der Webseite im selben Tab geöffnet werden. Das ist unüblich und etwas nervig, weil damit die gerade betrachtete Seite effektiv "geschlossen" wird.

Offenbar ist dieses "Fehlverhalten" ein lange bekannte Lücke im normalen GitHub-Markdown.
Immerhin soll es auf GitHub-Pages angeblich korrigierbar sein, siehe <https://stackoverflow.com/a/63546509>.

Dazu müsste auf Kramdown umgeschaltet werden, danach können wohl Links so angegeben werden, damit sie im neuen Tab geöffnet werden:

```Markdown
[Externer Link](https://example.com){:target="_blank" rel="noopener"}
```

(Auf den GitHub-Seiten selbst funktioniert das nicht, aber die meisten Besucher würden ja die GitHub-Page besuchen.)

@ckubgi , ggf. können wir das einfach mal probieren?
(Ich selbst habe keine Commit-Rechte...)

**Comment by ckubgi** [comment]
Danke für den Hinweis. Ich hab das für die Notizen zu HackyHour Nr. 12 jetzt so eingebaut und werde das in Zukunft so weiter führen. Ob ich alle Notizen nachpflege, weiß ich noch nicht. Dokumentiere ich hier ggf.
